# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
# ServiceProduct.create(:item_type=>"service", :name=>"Baseboards" ,:description=>"Paint baseboards",:active=>true )
# ServiceProduct.create(:item_type=>"service", :name=>"Ceiling" ,:description=>"Paint ceiling",:active=>true )
# ServiceProduct.create(:item_type=>"service", :name=>"Closets" ,:description=>"Paint closets",:active=>true )
# ServiceProduct.create(:item_type=>"service", :name=>"Door & Frame" ,:description=>"Paint door & frame",:active=>true )
# ServiceProduct.create(:item_type=>"service", :name=>"Floor" ,:description=>"Paint/Coat floor",:active=>true )
# ServiceProduct.create(:item_type=>"service", :name=>"new srvice quick book" ,:description=>"this is quick book test summary",:unit_cost=>"113.00",:active=>true )
# ServiceProduct.create(:item_type=>"service", :name=>"Primer" ,:description=>"Prime area in preparation for painting",:active=>true )
# ServiceProduct.create(:item_type=>"service", :name=>"Remove Paper" ,:description=>"Remove wall paper in preparation for painting",:active=>true )
# ServiceProduct.create(:item_type=>"service", :name=>"Remove Popcorn Ceiling" ,:description=>"Scrape ceiling in preparation for painting",:active=>true )
# ServiceProduct.create(:item_type=>"service", :name=>"Sales" ,:description=>"",:active=>true ,:non_taxable=>true)
# ServiceProduct.create(:item_type=>"service", :name=>"Test Pro" ,:description=>"",:active=>true ,:non_taxable=>true)
# ServiceProduct.create(:item_type=>"service", :name=>"Walls" ,:description=>"Paint walls",:active=>true )
# ServiceProduct.create(:item_type=>"service", :name=>"Window Trim" ,:description=>"Paint window trim",:active=>true )
# CustomCategory.create(:category=>"fuel_mileage",:category_type=>"expenses")
# ActionType.create(:name => "Play text and repeat menu" , :code => "PTRM",:display_order => 10)
# ActionType.create(:name => "Play text" ,:code => "PT",:announcement_action => true,:display_order => 20)
# ActionType.create(:name => "Play custom media file and repeat menu" , :code => "PMRM",:display_order => 30)
# ActionType.create(:name => "Play custom media file",:code => "PM",:announcement_action => true,:display_order => 40)
# ActionType.create(:name => "Play text and transfer to phone number",:code => "PTTN",:display_order => 50)
# ActionType.create(:name => "Transfer to phone number",:code => "TN",:display_order => 60)
# ActionType.create(:name => "Play text and record caller",:code => "PTRC",:display_order => 70)
# ActionType.create(:name => "Repeat menu",:code => "RM",:display_order => 80)
# ActionType.create(:name => "Transfer to sub menu",:code => "TSB",:display_order => 90)
# ActionType.create(:name => "Exit",:code => "E",:display_order => 10)
# ActionType.create(:name => "No Action",:code => "NA",:display_order => 110)
# ActionType.create(:name => "Go to previous menu" , :display_order => 120 , :code => "GTPM" )
# ActionType.create(:name => "",:display_order=>75,:code=>"SMS")
# Digit.create(:name => "0")
# Digit.create(:name => "1")
# Digit.create(:name => "2")
# Digit.create(:name => "3")
# Digit.create(:name => "4")
# Digit.create(:name => "5")
# Digit.create(:name => "6")
# Digit.create(:name => "7")
# Digit.create(:name => "8")
# Digit.create(:name => "9")
# Digit.create(:name => "#")
# Digit.create(:name => "*")
# Ivr.all.update_all(:application_id => "AP98ca75b453141603fa76d7db706ac12e" , :name => "Demo" , :phone_number => "+12053901762")
# Ivr.all.update_all(:free => true)
# Ivr.all.each do |ivr|
#   Number.create(:phone_number => ivr.phone_number , :ivr_id => ivr.id)
# end
# Number.create(:account_sid=>"AC8f6b581e1381cb405ca1735a6900f524",:auth_token => "a5f7ae43162029c9e6bc1c7cc1f643b8",:phone_number=>"+15103445646",:phone_sid=>"PNfecee13ed43c00d98ef2636dc94c3959",:voice=>"http://58a6b0.ngrok.com/ivrs/42827CA66FD341BDBC180B4F6E7F1B74/twiml",:ivr_id=>1)
# Ivr.create(:name=>"Miky",:free=>true,:application_id=>"APf73601f883b6303d28c5f9413316278e",:uuid=>"42827ca66fd341bdbc180b4f6e7f1b74",:state=>"active")

# ActionType.create(:id=>7,:name=>'Play text',:code=>'PT',:announcement_action=>1,:display_order=>20)
# ActionType.create(:id=>8,:name=>'Play custom media file',:code=>'PM',:announcement_action=>1,:display_order=>40)
# ActionType.create(:id=>9,:name=>'Play text and transfer to phone number',:code=>'PTTN',:display_order=>50)
# ActionType.create(:id=>10,:name=>'Transfer to phone number',:code=>'TN',:display_order=>60)
# ActionType.create(:id=>11,:name=>'Play text and record caller',:code=>'PTRC',:display_order=>70)
# ActionType.create(:id=>12,:name=>'Repeat menu',:code=>'RM',:display_order=>80)
# ActionType.create(:id=>13,:name=>'Transfer to sub menu',:code=>'TSB',:display_order=>90)
# ActionType.create(:id=>14,:name=>'Exit',:code=>'E',:display_order=>100)
# ActionType.create(:id=>15,:name=>'No Action',:code=>'NA',:display_order=>110)
# ActionType.create(:id=>17,:name=>'Play text and repeat menu',:code=>'PTRM',:display_order=>10)
# ActionType.create(:id=>18,:name=>'Play custom media file and repeat menu',:code=>'PMRM',:display_order=>30)
# ActionType.create(:id=>19,:name=>'Send SMS to caller',:code=>'SMS',:display_order=>75)




# Key.create(:id=>452, :ivr_id=>1, :digit	=>'10',:action_type_id=> 7, :display_order=>1)
# Key.create(:id=>453, :ivr_id=>1, :digit	=>'0', :action_type_id=>15, :display_order=>11)
# Key.create(:id=>454, :ivr_id=>1, :digit	=>'1', :action_type_id=>9, :display_order=>2)
# Key.create(:id=>455, :ivr_id=>1, :digit	=>'2', :action_type_id=>7, :display_order=>3)
# Key.create(:id=>456, :ivr_id=>1, :digit	=>'3', :action_type_id=>11, :display_order=>4)
# Key.create(:id=>457, :ivr_id=>1, :digit	=>'4', :action_type_id=>15, :display_order=>5)
# Key.create(:id=>458, :ivr_id=>1, :digit	=>'5', :action_type_id=>15, :display_order=>6)
# Key.create(:id=>459, :ivr_id=>1, :digit	=>'6', :action_type_id=>15, :display_order=>7)
# KeyDescription.create(:description=>"Play text",:key_number=>0)
# KeyDescription.create(:description=>"Play custom media file and repeat menu",:key_number=>1)
# KeyDescription.create(:description=>"Play custom media file",:key_number=>2)
# KeyDescription.create(:description=>"Play text and transfer to phone number",:key_number=>3)
# KeyDescription.create(:description=>"Transfer to phone number",:key_number=>4)
# KeyDescription.create(:description=>"Play text and record caller",:key_number=>5)
# KeyDescription.create(:description=>"Send SMS to caller",:key_number=>6)
# KeyDescription.create(:description=>"Repeat menu",:key_number=>7)
# KeyDescription.create(:description=>"Transfer to sub menu",:key_number=>8)
# KeyDescription.create(:description=>"Exit",:key_number=>9)

# CustomCategory.create(:category=>"Customer",:category_type=>"timesheets")
# CustomCategory.create(:category=>"Travel",:category_type=>"timesheets")
# CustomCategory.create(:category=>"Admin",:category_type=>"timesheets")

#DEMO CLIENTS AND ITS PROPERTIES
# Client.create(:first_name=>"copper",:last_name=>"service",:company_name=>"field service",:street1=>"24825 Northern Blvd Ste 1J",:city=>"little-neck",:state=>"NY",:zip_code=>"11362-1280",:country=>"US",:mobile_number=>"555000999",:personal_email=>"copper@mailinator.com")
# Client.create(:first_name=>"james",:last_name=>"anderson",:company_name=>"fans club",:street1=>"3511B Farrington St",:city=>"flushing",:state=>"NY",:zip_code=>"11354-2841",:country=>"US",:mobile_number=>"3332220000",:personal_email=>"james@mailinator.com")
# Client.create(:first_name=>"jason",:last_name=>"richard",:company_name=>" yahoo",:street1=>"21337 39th Ave",:city=>"Bayside",:state=>"NY",:zip_code=>"11361-2071",:country=>"US",:mobile_number=>"5556324152",:personal_email=>"jason@mailinator.com")
# Client.create(:first_name=>"brain",:last_name=>"smith",:company_name=>" usa club",:street1=>"17625 Union Tpke",:city=>"Fresh Meadows",:state=>"NY",:zip_code=>"11366-1515",:country=>"US",:mobile_number=>"5556324510",:personal_email=>"brain@mailinator.com")
# Client.create(:first_name=>"john",:last_name=>"ceina",:company_name=>" wwf club",:street1=>"3763 83rd St",:city=>"Jackson Heights",:state=>"NY",:zip_code=>"11372-7146",:country=>"US",:mobile_number=>"5556663333",:personal_email=>"john@mailinator.com")

# Property.create(:street=>"24825 Northern Blvd Ste 1J",:city=>"little-neck",:state=>"NY",:zipcode=>"11362-1280",:country=>"US",:client_id=>1)
# Property.create(:street=>"424 W 44th St",:city=>"New York",:state=>"NY",:zipcode=>"10036-5205",:country=>"US",:client_id=>1)
# Property.create(:street=>"3511B Farrington St",:city=>"flushing",:state=>"NY",:zipcode=>"11354-2841",:country=>"US",:client_id=>2)
# Property.create(:street=>"150 W 22nd Street 11th Floor",:city=>"New York",:state=>"NY",:zipcode=>"10011-9413",:country=>"US",:client_id=>2)
# Property.create(:street=>"21337 39th Ave",:city=>"Bayside",:state=>"NY",:zipcode=>"11361-2071",:country=>"US",:client_id=>3)
# Property.create(:street=>"3 Cushing Drive",:city=>"Bridgewater",:state=>"NJ",:zipcode=>"08807-1495",:country=>"US",:client_id=>3)
# Property.create(:street=>"17625 Union Tpke",:city=>"Fresh Meadows",:state=>"NY",:zipcode=>"11366-1515",:country=>"US",:client_id=>4)
# Property.create(:street=>"266 Elmwood Ave",:city=>"Buffalo",:state=>"NY",:zipcode=>"14222-2202",:country=>"US",:client_id=>4)
# Property.create(:street=>"3763 83rd St",:city=>"Jackson Heights",:state=>"NY",:zipcode=>"11372-7146",:country=>"US",:client_id=>5)
# Property.create(:street=>"12 Victoria Way",:city=>"Kendall Park
# ",:state=>"NJ",:zipcode=>"08824-1811",:country=>"US",:client_id=>5)
